export const SET_NAME_PEOPLE = "SET_NAME_PEOPLE";
export const DELETE_NAME_PEOPLE = "DELETE_NAME_PEOPLE";

export const SET_NAME_SPECIES = "SET_NAME_SPECIES";
export const DELETE_NAME_SPECIES = "DELETE_NAME_SPECIES";

export const SET_NAME_STARSHIPS = "SET_NAME_STARSHIPS";
export const DELETE_NAME_STARSHIPS = "DELETE_NAME_STARSHIPS";

export const SET_NAME_VEHICLES = "SET_NAME_VEHICLES";
export const DELETE_NAME_VEHICLES = "DELETE_NAME_VEHICLES";